/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 39
#define LARGE_STATE_COUNT 4
#define SYMBOL_COUNT 37
#define ALIAS_COUNT 0
#define TOKEN_COUNT 19
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 3
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_integer_literal = 1,
  sym_float_literal = 2,
  anon_sym_true = 3,
  anon_sym_false = 4,
  anon_sym_DQUOTE = 5,
  anon_sym_POUND_DQUOTE = 6,
  anon_sym_DQUOTE_POUND = 7,
  anon_sym_POUND_POUND_DQUOTE = 8,
  anon_sym_DQUOTE_POUND_POUND = 9,
  anon_sym_POUND_POUND_POUND_DQUOTE = 10,
  anon_sym_DQUOTE_POUND_POUND_POUND = 11,
  sym__string_content = 12,
  aux_sym__extended_string_content_1_token1 = 13,
  sym_escape_sequence = 14,
  anon_sym_LBRACE = 15,
  anon_sym_RBRACE = 16,
  sym_doc_comment = 17,
  sym_comment = 18,
  sym_source_file = 19,
  sym__statement = 20,
  sym__expression = 21,
  sym_boolean_literal = 22,
  sym_string_literal = 23,
  sym__basic_string = 24,
  sym__extended_string_1 = 25,
  sym__extended_string_2 = 26,
  sym__extended_string_3 = 27,
  sym__extended_string_content_1 = 28,
  sym__extended_string_content_2 = 29,
  sym__extended_string_content_3 = 30,
  sym_string_interpolation = 31,
  aux_sym_source_file_repeat1 = 32,
  aux_sym__basic_string_repeat1 = 33,
  aux_sym__extended_string_1_repeat1 = 34,
  aux_sym__extended_string_2_repeat1 = 35,
  aux_sym__extended_string_3_repeat1 = 36,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_integer_literal] = "integer_literal",
  [sym_float_literal] = "float_literal",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [anon_sym_DQUOTE] = "\"",
  [anon_sym_POUND_DQUOTE] = "#\"",
  [anon_sym_DQUOTE_POUND] = "\"#",
  [anon_sym_POUND_POUND_DQUOTE] = "##\"",
  [anon_sym_DQUOTE_POUND_POUND] = "\"##",
  [anon_sym_POUND_POUND_POUND_DQUOTE] = "###\"",
  [anon_sym_DQUOTE_POUND_POUND_POUND] = "\"###",
  [sym__string_content] = "_string_content",
  [aux_sym__extended_string_content_1_token1] = "_extended_string_content_1_token1",
  [sym_escape_sequence] = "escape_sequence",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [sym_doc_comment] = "doc_comment",
  [sym_comment] = "comment",
  [sym_source_file] = "source_file",
  [sym__statement] = "_statement",
  [sym__expression] = "_expression",
  [sym_boolean_literal] = "boolean_literal",
  [sym_string_literal] = "string_literal",
  [sym__basic_string] = "_basic_string",
  [sym__extended_string_1] = "_extended_string_1",
  [sym__extended_string_2] = "_extended_string_2",
  [sym__extended_string_3] = "_extended_string_3",
  [sym__extended_string_content_1] = "_extended_string_content_1",
  [sym__extended_string_content_2] = "_extended_string_content_2",
  [sym__extended_string_content_3] = "_extended_string_content_3",
  [sym_string_interpolation] = "string_interpolation",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym__basic_string_repeat1] = "_basic_string_repeat1",
  [aux_sym__extended_string_1_repeat1] = "_extended_string_1_repeat1",
  [aux_sym__extended_string_2_repeat1] = "_extended_string_2_repeat1",
  [aux_sym__extended_string_3_repeat1] = "_extended_string_3_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_integer_literal] = sym_integer_literal,
  [sym_float_literal] = sym_float_literal,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [anon_sym_POUND_DQUOTE] = anon_sym_POUND_DQUOTE,
  [anon_sym_DQUOTE_POUND] = anon_sym_DQUOTE_POUND,
  [anon_sym_POUND_POUND_DQUOTE] = anon_sym_POUND_POUND_DQUOTE,
  [anon_sym_DQUOTE_POUND_POUND] = anon_sym_DQUOTE_POUND_POUND,
  [anon_sym_POUND_POUND_POUND_DQUOTE] = anon_sym_POUND_POUND_POUND_DQUOTE,
  [anon_sym_DQUOTE_POUND_POUND_POUND] = anon_sym_DQUOTE_POUND_POUND_POUND,
  [sym__string_content] = sym__string_content,
  [aux_sym__extended_string_content_1_token1] = aux_sym__extended_string_content_1_token1,
  [sym_escape_sequence] = sym_escape_sequence,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [sym_doc_comment] = sym_doc_comment,
  [sym_comment] = sym_comment,
  [sym_source_file] = sym_source_file,
  [sym__statement] = sym__statement,
  [sym__expression] = sym__expression,
  [sym_boolean_literal] = sym_boolean_literal,
  [sym_string_literal] = sym_string_literal,
  [sym__basic_string] = sym__basic_string,
  [sym__extended_string_1] = sym__extended_string_1,
  [sym__extended_string_2] = sym__extended_string_2,
  [sym__extended_string_3] = sym__extended_string_3,
  [sym__extended_string_content_1] = sym__extended_string_content_1,
  [sym__extended_string_content_2] = sym__extended_string_content_2,
  [sym__extended_string_content_3] = sym__extended_string_content_3,
  [sym_string_interpolation] = sym_string_interpolation,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym__basic_string_repeat1] = aux_sym__basic_string_repeat1,
  [aux_sym__extended_string_1_repeat1] = aux_sym__extended_string_1_repeat1,
  [aux_sym__extended_string_2_repeat1] = aux_sym__extended_string_2_repeat1,
  [aux_sym__extended_string_3_repeat1] = aux_sym__extended_string_3_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_integer_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_float_literal] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUND_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DQUOTE_POUND] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUND_POUND_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DQUOTE_POUND_POUND] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUND_POUND_POUND_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DQUOTE_POUND_POUND_POUND] = {
    .visible = true,
    .named = false,
  },
  [sym__string_content] = {
    .visible = false,
    .named = true,
  },
  [aux_sym__extended_string_content_1_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_escape_sequence] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [sym_doc_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__statement] = {
    .visible = false,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [sym_boolean_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_string_literal] = {
    .visible = true,
    .named = true,
  },
  [sym__basic_string] = {
    .visible = false,
    .named = true,
  },
  [sym__extended_string_1] = {
    .visible = false,
    .named = true,
  },
  [sym__extended_string_2] = {
    .visible = false,
    .named = true,
  },
  [sym__extended_string_3] = {
    .visible = false,
    .named = true,
  },
  [sym__extended_string_content_1] = {
    .visible = false,
    .named = true,
  },
  [sym__extended_string_content_2] = {
    .visible = false,
    .named = true,
  },
  [sym__extended_string_content_3] = {
    .visible = false,
    .named = true,
  },
  [sym_string_interpolation] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__basic_string_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__extended_string_1_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__extended_string_2_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__extended_string_3_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 4,
  [6] = 4,
  [7] = 4,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 30,
  [32] = 30,
  [33] = 30,
  [34] = 34,
  [35] = 35,
  [36] = 35,
  [37] = 35,
  [38] = 35,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(25);
      ADVANCE_MAP(
        '"', 30,
        '#', 2,
        '/', 14,
        '\\', 22,
        'f', 15,
        't', 19,
        '{', 49,
        '}', 50,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(24);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(26);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(30);
      if (lookahead == '/') ADVANCE(40);
      if (lookahead == '\\') ADVANCE(22);
      if (lookahead == '{') ADVANCE(49);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(39);
      if (lookahead != 0) ADVANCE(41);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(31);
      if (lookahead == '#') ADVANCE(3);
      END_STATE();
    case 3:
      if (lookahead == '"') ADVANCE(33);
      if (lookahead == '#') ADVANCE(4);
      END_STATE();
    case 4:
      if (lookahead == '"') ADVANCE(35);
      END_STATE();
    case 5:
      if (lookahead == '"') ADVANCE(13);
      if (lookahead == '/') ADVANCE(46);
      if (lookahead == '{') ADVANCE(49);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(45);
      if (lookahead != 0) ADVANCE(47);
      END_STATE();
    case 6:
      if (lookahead == '"') ADVANCE(10);
      if (lookahead == '/') ADVANCE(46);
      if (lookahead == '{') ADVANCE(49);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(45);
      if (lookahead != 0) ADVANCE(47);
      END_STATE();
    case 7:
      if (lookahead == '"') ADVANCE(12);
      if (lookahead == '/') ADVANCE(46);
      if (lookahead == '{') ADVANCE(49);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(45);
      if (lookahead != 0) ADVANCE(47);
      END_STATE();
    case 8:
      if (lookahead == '#') ADVANCE(36);
      END_STATE();
    case 9:
      if (lookahead == '#') ADVANCE(34);
      END_STATE();
    case 10:
      if (lookahead == '#') ADVANCE(32);
      END_STATE();
    case 11:
      if (lookahead == '#') ADVANCE(8);
      END_STATE();
    case 12:
      if (lookahead == '#') ADVANCE(9);
      END_STATE();
    case 13:
      if (lookahead == '#') ADVANCE(11);
      END_STATE();
    case 14:
      if (lookahead == '/') ADVANCE(52);
      END_STATE();
    case 15:
      if (lookahead == 'a') ADVANCE(18);
      END_STATE();
    case 16:
      if (lookahead == 'e') ADVANCE(28);
      END_STATE();
    case 17:
      if (lookahead == 'e') ADVANCE(29);
      END_STATE();
    case 18:
      if (lookahead == 'l') ADVANCE(20);
      END_STATE();
    case 19:
      if (lookahead == 'r') ADVANCE(21);
      END_STATE();
    case 20:
      if (lookahead == 's') ADVANCE(17);
      END_STATE();
    case 21:
      if (lookahead == 'u') ADVANCE(16);
      END_STATE();
    case 22:
      if (lookahead == '"' ||
          lookahead == '\\' ||
          lookahead == 'n' ||
          lookahead == 'r' ||
          lookahead == 't' ||
          lookahead == '{') ADVANCE(48);
      END_STATE();
    case 23:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(27);
      END_STATE();
    case 24:
      if (eof) ADVANCE(25);
      if (lookahead == '"') ADVANCE(30);
      if (lookahead == '#') ADVANCE(2);
      if (lookahead == '/') ADVANCE(14);
      if (lookahead == 'f') ADVANCE(15);
      if (lookahead == 't') ADVANCE(19);
      if (lookahead == '{') ADVANCE(49);
      if (lookahead == '}') ADVANCE(50);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(24);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(26);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_integer_literal);
      if (lookahead == '.') ADVANCE(23);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(26);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_float_literal);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(27);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_true);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_false);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_POUND_DQUOTE);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_DQUOTE_POUND);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_POUND_POUND_DQUOTE);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_DQUOTE_POUND_POUND);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_POUND_POUND_POUND_DQUOTE);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_DQUOTE_POUND_POUND_POUND);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym__string_content);
      if (lookahead == '\n') ADVANCE(41);
      if (lookahead == '/') ADVANCE(38);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\' &&
          lookahead != '{') ADVANCE(38);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym__string_content);
      if (lookahead == '\n') ADVANCE(41);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\' &&
          lookahead != '{') ADVANCE(38);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym__string_content);
      if (lookahead == '/') ADVANCE(40);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(39);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\' &&
          lookahead != '{') ADVANCE(41);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym__string_content);
      if (lookahead == '/') ADVANCE(37);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\' &&
          lookahead != '{') ADVANCE(41);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym__string_content);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\\' &&
          lookahead != '{') ADVANCE(41);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(aux_sym__extended_string_content_1_token1);
      if (lookahead == '\n') ADVANCE(47);
      if (lookahead == '/') ADVANCE(43);
      if (lookahead == '"' ||
          lookahead == '{') ADVANCE(53);
      if (lookahead != 0) ADVANCE(44);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(aux_sym__extended_string_content_1_token1);
      if (lookahead == '\n') ADVANCE(47);
      if (lookahead == '"' ||
          lookahead == '{') ADVANCE(51);
      if (lookahead != 0) ADVANCE(43);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(aux_sym__extended_string_content_1_token1);
      if (lookahead == '\n') ADVANCE(47);
      if (lookahead == '"' ||
          lookahead == '{') ADVANCE(53);
      if (lookahead != 0) ADVANCE(44);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(aux_sym__extended_string_content_1_token1);
      if (lookahead == '/') ADVANCE(46);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(45);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '{') ADVANCE(47);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(aux_sym__extended_string_content_1_token1);
      if (lookahead == '/') ADVANCE(42);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '{') ADVANCE(47);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(aux_sym__extended_string_content_1_token1);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '{') ADVANCE(47);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_escape_sequence);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_doc_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(51);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == '/') ADVANCE(51);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(53);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(53);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 5},
  [19] = {.lex_state = 7},
  [20] = {.lex_state = 7},
  [21] = {.lex_state = 5},
  [22] = {.lex_state = 1},
  [23] = {.lex_state = 1},
  [24] = {.lex_state = 6},
  [25] = {.lex_state = 6},
  [26] = {.lex_state = 1},
  [27] = {.lex_state = 6},
  [28] = {.lex_state = 7},
  [29] = {.lex_state = 5},
  [30] = {.lex_state = 1},
  [31] = {.lex_state = 5},
  [32] = {.lex_state = 7},
  [33] = {.lex_state = 6},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_integer_literal] = ACTIONS(1),
    [sym_float_literal] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_POUND_DQUOTE] = ACTIONS(1),
    [anon_sym_POUND_POUND_DQUOTE] = ACTIONS(1),
    [anon_sym_POUND_POUND_POUND_DQUOTE] = ACTIONS(1),
    [sym_escape_sequence] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [sym_doc_comment] = ACTIONS(3),
    [sym_comment] = ACTIONS(5),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(34),
    [sym__statement] = STATE(2),
    [sym__expression] = STATE(2),
    [sym_boolean_literal] = STATE(2),
    [sym_string_literal] = STATE(2),
    [sym__basic_string] = STATE(10),
    [sym__extended_string_1] = STATE(10),
    [sym__extended_string_2] = STATE(10),
    [sym__extended_string_3] = STATE(10),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(7),
    [sym_integer_literal] = ACTIONS(9),
    [sym_float_literal] = ACTIONS(11),
    [anon_sym_true] = ACTIONS(13),
    [anon_sym_false] = ACTIONS(13),
    [anon_sym_DQUOTE] = ACTIONS(15),
    [anon_sym_POUND_DQUOTE] = ACTIONS(17),
    [anon_sym_POUND_POUND_DQUOTE] = ACTIONS(19),
    [anon_sym_POUND_POUND_POUND_DQUOTE] = ACTIONS(21),
    [sym_doc_comment] = ACTIONS(3),
    [sym_comment] = ACTIONS(5),
  },
  [STATE(2)] = {
    [sym__statement] = STATE(3),
    [sym__expression] = STATE(3),
    [sym_boolean_literal] = STATE(3),
    [sym_string_literal] = STATE(3),
    [sym__basic_string] = STATE(10),
    [sym__extended_string_1] = STATE(10),
    [sym__extended_string_2] = STATE(10),
    [sym__extended_string_3] = STATE(10),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(23),
    [sym_integer_literal] = ACTIONS(25),
    [sym_float_literal] = ACTIONS(27),
    [anon_sym_true] = ACTIONS(13),
    [anon_sym_false] = ACTIONS(13),
    [anon_sym_DQUOTE] = ACTIONS(15),
    [anon_sym_POUND_DQUOTE] = ACTIONS(17),
    [anon_sym_POUND_POUND_DQUOTE] = ACTIONS(19),
    [anon_sym_POUND_POUND_POUND_DQUOTE] = ACTIONS(21),
    [sym_doc_comment] = ACTIONS(3),
    [sym_comment] = ACTIONS(5),
  },
  [STATE(3)] = {
    [sym__statement] = STATE(3),
    [sym__expression] = STATE(3),
    [sym_boolean_literal] = STATE(3),
    [sym_string_literal] = STATE(3),
    [sym__basic_string] = STATE(10),
    [sym__extended_string_1] = STATE(10),
    [sym__extended_string_2] = STATE(10),
    [sym__extended_string_3] = STATE(10),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(29),
    [sym_integer_literal] = ACTIONS(31),
    [sym_float_literal] = ACTIONS(34),
    [anon_sym_true] = ACTIONS(37),
    [anon_sym_false] = ACTIONS(37),
    [anon_sym_DQUOTE] = ACTIONS(40),
    [anon_sym_POUND_DQUOTE] = ACTIONS(43),
    [anon_sym_POUND_POUND_DQUOTE] = ACTIONS(46),
    [anon_sym_POUND_POUND_POUND_DQUOTE] = ACTIONS(49),
    [sym_doc_comment] = ACTIONS(3),
    [sym_comment] = ACTIONS(5),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 11,
    ACTIONS(3), 1,
      sym_doc_comment,
    ACTIONS(5), 1,
      sym_comment,
    ACTIONS(15), 1,
      anon_sym_DQUOTE,
    ACTIONS(17), 1,
      anon_sym_POUND_DQUOTE,
    ACTIONS(19), 1,
      anon_sym_POUND_POUND_DQUOTE,
    ACTIONS(21), 1,
      anon_sym_POUND_POUND_POUND_DQUOTE,
    ACTIONS(52), 1,
      sym_integer_literal,
    ACTIONS(54), 1,
      sym_float_literal,
    ACTIONS(13), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(35), 3,
      sym__expression,
      sym_boolean_literal,
      sym_string_literal,
    STATE(10), 4,
      sym__basic_string,
      sym__extended_string_1,
      sym__extended_string_2,
      sym__extended_string_3,
  [40] = 11,
    ACTIONS(3), 1,
      sym_doc_comment,
    ACTIONS(5), 1,
      sym_comment,
    ACTIONS(15), 1,
      anon_sym_DQUOTE,
    ACTIONS(17), 1,
      anon_sym_POUND_DQUOTE,
    ACTIONS(19), 1,
      anon_sym_POUND_POUND_DQUOTE,
    ACTIONS(21), 1,
      anon_sym_POUND_POUND_POUND_DQUOTE,
    ACTIONS(56), 1,
      sym_integer_literal,
    ACTIONS(58), 1,
      sym_float_literal,
    ACTIONS(13), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(37), 3,
      sym__expression,
      sym_boolean_literal,
      sym_string_literal,
    STATE(10), 4,
      sym__basic_string,
      sym__extended_string_1,
      sym__extended_string_2,
      sym__extended_string_3,
  [80] = 11,
    ACTIONS(3), 1,
      sym_doc_comment,
    ACTIONS(5), 1,
      sym_comment,
    ACTIONS(15), 1,
      anon_sym_DQUOTE,
    ACTIONS(17), 1,
      anon_sym_POUND_DQUOTE,
    ACTIONS(19), 1,
      anon_sym_POUND_POUND_DQUOTE,
    ACTIONS(21), 1,
      anon_sym_POUND_POUND_POUND_DQUOTE,
    ACTIONS(60), 1,
      sym_integer_literal,
    ACTIONS(62), 1,
      sym_float_literal,
    ACTIONS(13), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(38), 3,
      sym__expression,
      sym_boolean_literal,
      sym_string_literal,
    STATE(10), 4,
      sym__basic_string,
      sym__extended_string_1,
      sym__extended_string_2,
      sym__extended_string_3,
  [120] = 11,
    ACTIONS(3), 1,
      sym_doc_comment,
    ACTIONS(5), 1,
      sym_comment,
    ACTIONS(15), 1,
      anon_sym_DQUOTE,
    ACTIONS(17), 1,
      anon_sym_POUND_DQUOTE,
    ACTIONS(19), 1,
      anon_sym_POUND_POUND_DQUOTE,
    ACTIONS(21), 1,
      anon_sym_POUND_POUND_POUND_DQUOTE,
    ACTIONS(64), 1,
      sym_integer_literal,
    ACTIONS(66), 1,
      sym_float_literal,
    ACTIONS(13), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(36), 3,
      sym__expression,
      sym_boolean_literal,
      sym_string_literal,
    STATE(10), 4,
      sym__basic_string,
      sym__extended_string_1,
      sym__extended_string_2,
      sym__extended_string_3,
  [160] = 4,
    ACTIONS(3), 1,
      sym_doc_comment,
    ACTIONS(5), 1,
      sym_comment,
    ACTIONS(70), 1,
      sym_integer_literal,
    ACTIONS(68), 9,
      ts_builtin_sym_end,
      sym_float_literal,
      anon_sym_true,
      anon_sym_false,
      anon_sym_DQUOTE,
      anon_sym_POUND_DQUOTE,
      anon_sym_POUND_POUND_DQUOTE,
      anon_sym_POUND_POUND_POUND_DQUOTE,
      anon_sym_RBRACE,
  [181] = 4,
    ACTIONS(3), 1,
      sym_doc_comment,
    ACTIONS(5), 1,
      sym_comment,
    ACTIONS(74), 1,
      sym_integer_literal,
    ACTIONS(72), 9,
      ts_builtin_sym_end,
      sym_float_literal,
      anon_sym_true,
      anon_sym_false,
      anon_sym_DQUOTE,
      anon_sym_POUND_DQUOTE,
      anon_sym_POUND_POUND_DQUOTE,
      anon_sym_POUND_POUND_POUND_DQUOTE,
      anon_sym_RBRACE,
  [202] = 4,
    ACTIONS(3), 1,
      sym_doc_comment,
    ACTIONS(5), 1,
      sym_comment,
    ACTIONS(78), 1,
      sym_integer_literal,
    ACTIONS(76), 9,
      ts_builtin_sym_end,
      sym_float_literal,
      anon_sym_true,
      anon_sym_false,
      anon_sym_DQUOTE,
      anon_sym_POUND_DQUOTE,
      anon_sym_POUND_POUND_DQUOTE,
      anon_sym_POUND_POUND_POUND_DQUOTE,
      anon_sym_RBRACE,
  [223] = 4,
    ACTIONS(3), 1,
      sym_doc_comment,
    ACTIONS(5), 1,
      sym_comment,
    ACTIONS(82), 1,
      sym_integer_literal,
    ACTIONS(80), 9,
      ts_builtin_sym_end,
      sym_float_literal,
      anon_sym_true,
      anon_sym_false,
      anon_sym_DQUOTE,
      anon_sym_POUND_DQUOTE,
      anon_sym_POUND_POUND_DQUOTE,
      anon_sym_POUND_POUND_POUND_DQUOTE,
      anon_sym_RBRACE,
  [244] = 4,
    ACTIONS(3), 1,
      sym_doc_comment,
    ACTIONS(5), 1,
      sym_comment,
    ACTIONS(86), 1,
      sym_integer_literal,
    ACTIONS(84), 9,
      ts_builtin_sym_end,
      sym_float_literal,
      anon_sym_true,
      anon_sym_false,
      anon_sym_DQUOTE,
      anon_sym_POUND_DQUOTE,
      anon_sym_POUND_POUND_DQUOTE,
      anon_sym_POUND_POUND_POUND_DQUOTE,
      anon_sym_RBRACE,
  [265] = 4,
    ACTIONS(3), 1,
      sym_doc_comment,
    ACTIONS(5), 1,
      sym_comment,
    ACTIONS(90), 1,
      sym_integer_literal,
    ACTIONS(88), 9,
      ts_builtin_sym_end,
      sym_float_literal,
      anon_sym_true,
      anon_sym_false,
      anon_sym_DQUOTE,
      anon_sym_POUND_DQUOTE,
      anon_sym_POUND_POUND_DQUOTE,
      anon_sym_POUND_POUND_POUND_DQUOTE,
      anon_sym_RBRACE,
  [286] = 4,
    ACTIONS(3), 1,
      sym_doc_comment,
    ACTIONS(5), 1,
      sym_comment,
    ACTIONS(94), 1,
      sym_integer_literal,
    ACTIONS(92), 9,
      ts_builtin_sym_end,
      sym_float_literal,
      anon_sym_true,
      anon_sym_false,
      anon_sym_DQUOTE,
      anon_sym_POUND_DQUOTE,
      anon_sym_POUND_POUND_DQUOTE,
      anon_sym_POUND_POUND_POUND_DQUOTE,
      anon_sym_RBRACE,
  [307] = 4,
    ACTIONS(3), 1,
      sym_doc_comment,
    ACTIONS(5), 1,
      sym_comment,
    ACTIONS(98), 1,
      sym_integer_literal,
    ACTIONS(96), 9,
      ts_builtin_sym_end,
      sym_float_literal,
      anon_sym_true,
      anon_sym_false,
      anon_sym_DQUOTE,
      anon_sym_POUND_DQUOTE,
      anon_sym_POUND_POUND_DQUOTE,
      anon_sym_POUND_POUND_POUND_DQUOTE,
      anon_sym_RBRACE,
  [328] = 4,
    ACTIONS(3), 1,
      sym_doc_comment,
    ACTIONS(5), 1,
      sym_comment,
    ACTIONS(102), 1,
      sym_integer_literal,
    ACTIONS(100), 9,
      ts_builtin_sym_end,
      sym_float_literal,
      anon_sym_true,
      anon_sym_false,
      anon_sym_DQUOTE,
      anon_sym_POUND_DQUOTE,
      anon_sym_POUND_POUND_DQUOTE,
      anon_sym_POUND_POUND_POUND_DQUOTE,
      anon_sym_RBRACE,
  [349] = 4,
    ACTIONS(3), 1,
      sym_doc_comment,
    ACTIONS(5), 1,
      sym_comment,
    ACTIONS(106), 1,
      sym_integer_literal,
    ACTIONS(104), 9,
      ts_builtin_sym_end,
      sym_float_literal,
      anon_sym_true,
      anon_sym_false,
      anon_sym_DQUOTE,
      anon_sym_POUND_DQUOTE,
      anon_sym_POUND_POUND_DQUOTE,
      anon_sym_POUND_POUND_POUND_DQUOTE,
      anon_sym_RBRACE,
  [370] = 5,
    ACTIONS(108), 1,
      anon_sym_DQUOTE_POUND_POUND_POUND,
    ACTIONS(110), 1,
      aux_sym__extended_string_content_1_token1,
    ACTIONS(113), 1,
      anon_sym_LBRACE,
    ACTIONS(5), 2,
      sym_doc_comment,
      sym_comment,
    STATE(18), 3,
      sym__extended_string_content_3,
      sym_string_interpolation,
      aux_sym__extended_string_3_repeat1,
  [389] = 5,
    ACTIONS(116), 1,
      anon_sym_DQUOTE_POUND_POUND,
    ACTIONS(118), 1,
      aux_sym__extended_string_content_1_token1,
    ACTIONS(120), 1,
      anon_sym_LBRACE,
    ACTIONS(5), 2,
      sym_doc_comment,
      sym_comment,
    STATE(28), 3,
      sym__extended_string_content_2,
      sym_string_interpolation,
      aux_sym__extended_string_2_repeat1,
  [408] = 5,
    ACTIONS(122), 1,
      anon_sym_DQUOTE_POUND_POUND,
    ACTIONS(124), 1,
      aux_sym__extended_string_content_1_token1,
    ACTIONS(127), 1,
      anon_sym_LBRACE,
    ACTIONS(5), 2,
      sym_doc_comment,
      sym_comment,
    STATE(20), 3,
      sym__extended_string_content_2,
      sym_string_interpolation,
      aux_sym__extended_string_2_repeat1,
  [427] = 5,
    ACTIONS(130), 1,
      anon_sym_DQUOTE_POUND_POUND_POUND,
    ACTIONS(132), 1,
      aux_sym__extended_string_content_1_token1,
    ACTIONS(134), 1,
      anon_sym_LBRACE,
    ACTIONS(5), 2,
      sym_doc_comment,
      sym_comment,
    STATE(29), 3,
      sym__extended_string_content_3,
      sym_string_interpolation,
      aux_sym__extended_string_3_repeat1,
  [446] = 5,
    ACTIONS(136), 1,
      anon_sym_DQUOTE,
    ACTIONS(141), 1,
      anon_sym_LBRACE,
    ACTIONS(5), 2,
      sym_doc_comment,
      sym_comment,
    ACTIONS(138), 2,
      sym__string_content,
      sym_escape_sequence,
    STATE(22), 2,
      sym_string_interpolation,
      aux_sym__basic_string_repeat1,
  [465] = 5,
    ACTIONS(144), 1,
      anon_sym_DQUOTE,
    ACTIONS(148), 1,
      anon_sym_LBRACE,
    ACTIONS(5), 2,
      sym_doc_comment,
      sym_comment,
    ACTIONS(146), 2,
      sym__string_content,
      sym_escape_sequence,
    STATE(22), 2,
      sym_string_interpolation,
      aux_sym__basic_string_repeat1,
  [484] = 5,
    ACTIONS(150), 1,
      anon_sym_DQUOTE_POUND,
    ACTIONS(152), 1,
      aux_sym__extended_string_content_1_token1,
    ACTIONS(155), 1,
      anon_sym_LBRACE,
    ACTIONS(5), 2,
      sym_doc_comment,
      sym_comment,
    STATE(24), 3,
      sym__extended_string_content_1,
      sym_string_interpolation,
      aux_sym__extended_string_1_repeat1,
  [503] = 5,
    ACTIONS(158), 1,
      anon_sym_DQUOTE_POUND,
    ACTIONS(160), 1,
      aux_sym__extended_string_content_1_token1,
    ACTIONS(162), 1,
      anon_sym_LBRACE,
    ACTIONS(5), 2,
      sym_doc_comment,
      sym_comment,
    STATE(24), 3,
      sym__extended_string_content_1,
      sym_string_interpolation,
      aux_sym__extended_string_1_repeat1,
  [522] = 5,
    ACTIONS(148), 1,
      anon_sym_LBRACE,
    ACTIONS(164), 1,
      anon_sym_DQUOTE,
    ACTIONS(5), 2,
      sym_doc_comment,
      sym_comment,
    ACTIONS(166), 2,
      sym__string_content,
      sym_escape_sequence,
    STATE(23), 2,
      sym_string_interpolation,
      aux_sym__basic_string_repeat1,
  [541] = 5,
    ACTIONS(162), 1,
      anon_sym_LBRACE,
    ACTIONS(168), 1,
      anon_sym_DQUOTE_POUND,
    ACTIONS(170), 1,
      aux_sym__extended_string_content_1_token1,
    ACTIONS(5), 2,
      sym_doc_comment,
      sym_comment,
    STATE(25), 3,
      sym__extended_string_content_1,
      sym_string_interpolation,
      aux_sym__extended_string_1_repeat1,
  [560] = 5,
    ACTIONS(120), 1,
      anon_sym_LBRACE,
    ACTIONS(172), 1,
      anon_sym_DQUOTE_POUND_POUND,
    ACTIONS(174), 1,
      aux_sym__extended_string_content_1_token1,
    ACTIONS(5), 2,
      sym_doc_comment,
      sym_comment,
    STATE(20), 3,
      sym__extended_string_content_2,
      sym_string_interpolation,
      aux_sym__extended_string_2_repeat1,
  [579] = 5,
    ACTIONS(134), 1,
      anon_sym_LBRACE,
    ACTIONS(176), 1,
      anon_sym_DQUOTE_POUND_POUND_POUND,
    ACTIONS(178), 1,
      aux_sym__extended_string_content_1_token1,
    ACTIONS(5), 2,
      sym_doc_comment,
      sym_comment,
    STATE(18), 3,
      sym__extended_string_content_3,
      sym_string_interpolation,
      aux_sym__extended_string_3_repeat1,
  [598] = 3,
    ACTIONS(5), 2,
      sym_doc_comment,
      sym_comment,
    ACTIONS(180), 2,
      anon_sym_DQUOTE,
      anon_sym_LBRACE,
    ACTIONS(182), 2,
      sym__string_content,
      sym_escape_sequence,
  [611] = 2,
    ACTIONS(5), 2,
      sym_doc_comment,
      sym_comment,
    ACTIONS(180), 3,
      anon_sym_DQUOTE_POUND_POUND_POUND,
      aux_sym__extended_string_content_1_token1,
      anon_sym_LBRACE,
  [621] = 2,
    ACTIONS(5), 2,
      sym_doc_comment,
      sym_comment,
    ACTIONS(180), 3,
      anon_sym_DQUOTE_POUND_POUND,
      aux_sym__extended_string_content_1_token1,
      anon_sym_LBRACE,
  [631] = 2,
    ACTIONS(5), 2,
      sym_doc_comment,
      sym_comment,
    ACTIONS(180), 3,
      anon_sym_DQUOTE_POUND,
      aux_sym__extended_string_content_1_token1,
      anon_sym_LBRACE,
  [641] = 3,
    ACTIONS(3), 1,
      sym_doc_comment,
    ACTIONS(5), 1,
      sym_comment,
    ACTIONS(184), 1,
      ts_builtin_sym_end,
  [651] = 3,
    ACTIONS(3), 1,
      sym_doc_comment,
    ACTIONS(5), 1,
      sym_comment,
    ACTIONS(186), 1,
      anon_sym_RBRACE,
  [661] = 3,
    ACTIONS(3), 1,
      sym_doc_comment,
    ACTIONS(5), 1,
      sym_comment,
    ACTIONS(188), 1,
      anon_sym_RBRACE,
  [671] = 3,
    ACTIONS(3), 1,
      sym_doc_comment,
    ACTIONS(5), 1,
      sym_comment,
    ACTIONS(190), 1,
      anon_sym_RBRACE,
  [681] = 3,
    ACTIONS(3), 1,
      sym_doc_comment,
    ACTIONS(5), 1,
      sym_comment,
    ACTIONS(192), 1,
      anon_sym_RBRACE,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(4)] = 0,
  [SMALL_STATE(5)] = 40,
  [SMALL_STATE(6)] = 80,
  [SMALL_STATE(7)] = 120,
  [SMALL_STATE(8)] = 160,
  [SMALL_STATE(9)] = 181,
  [SMALL_STATE(10)] = 202,
  [SMALL_STATE(11)] = 223,
  [SMALL_STATE(12)] = 244,
  [SMALL_STATE(13)] = 265,
  [SMALL_STATE(14)] = 286,
  [SMALL_STATE(15)] = 307,
  [SMALL_STATE(16)] = 328,
  [SMALL_STATE(17)] = 349,
  [SMALL_STATE(18)] = 370,
  [SMALL_STATE(19)] = 389,
  [SMALL_STATE(20)] = 408,
  [SMALL_STATE(21)] = 427,
  [SMALL_STATE(22)] = 446,
  [SMALL_STATE(23)] = 465,
  [SMALL_STATE(24)] = 484,
  [SMALL_STATE(25)] = 503,
  [SMALL_STATE(26)] = 522,
  [SMALL_STATE(27)] = 541,
  [SMALL_STATE(28)] = 560,
  [SMALL_STATE(29)] = 579,
  [SMALL_STATE(30)] = 598,
  [SMALL_STATE(31)] = 611,
  [SMALL_STATE(32)] = 621,
  [SMALL_STATE(33)] = 631,
  [SMALL_STATE(34)] = 641,
  [SMALL_STATE(35)] = 651,
  [SMALL_STATE(36)] = 661,
  [SMALL_STATE(37)] = 671,
  [SMALL_STATE(38)] = 681,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [7] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [29] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [31] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [34] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [37] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(8),
  [40] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(26),
  [43] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(27),
  [46] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(19),
  [49] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(21),
  [52] = {.entry = {.count = 1, .reusable = false}}, SHIFT(35),
  [54] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [56] = {.entry = {.count = 1, .reusable = false}}, SHIFT(37),
  [58] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [60] = {.entry = {.count = 1, .reusable = false}}, SHIFT(38),
  [62] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [64] = {.entry = {.count = 1, .reusable = false}}, SHIFT(36),
  [66] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [68] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_boolean_literal, 1, 0, 0),
  [70] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_boolean_literal, 1, 0, 0),
  [72] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__basic_string, 2, 0, 0),
  [74] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__basic_string, 2, 0, 0),
  [76] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string_literal, 1, 0, 0),
  [78] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string_literal, 1, 0, 0),
  [80] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__extended_string_1, 2, 0, 0),
  [82] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__extended_string_1, 2, 0, 0),
  [84] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__extended_string_2, 2, 0, 0),
  [86] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__extended_string_2, 2, 0, 0),
  [88] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__extended_string_3, 2, 0, 0),
  [90] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__extended_string_3, 2, 0, 0),
  [92] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__extended_string_2, 3, 0, 0),
  [94] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__extended_string_2, 3, 0, 0),
  [96] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__extended_string_1, 3, 0, 0),
  [98] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__extended_string_1, 3, 0, 0),
  [100] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__basic_string, 3, 0, 0),
  [102] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__basic_string, 3, 0, 0),
  [104] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__extended_string_3, 3, 0, 0),
  [106] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__extended_string_3, 3, 0, 0),
  [108] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__extended_string_3_repeat1, 2, 0, 0),
  [110] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__extended_string_3_repeat1, 2, 0, 0), SHIFT_REPEAT(18),
  [113] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__extended_string_3_repeat1, 2, 0, 0), SHIFT_REPEAT(7),
  [116] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [118] = {.entry = {.count = 1, .reusable = false}}, SHIFT(28),
  [120] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [122] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__extended_string_2_repeat1, 2, 0, 0),
  [124] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__extended_string_2_repeat1, 2, 0, 0), SHIFT_REPEAT(20),
  [127] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__extended_string_2_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [130] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [132] = {.entry = {.count = 1, .reusable = false}}, SHIFT(29),
  [134] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [136] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__basic_string_repeat1, 2, 0, 0),
  [138] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__basic_string_repeat1, 2, 0, 0), SHIFT_REPEAT(22),
  [141] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__basic_string_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [144] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [146] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [148] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [150] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__extended_string_1_repeat1, 2, 0, 0),
  [152] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__extended_string_1_repeat1, 2, 0, 0), SHIFT_REPEAT(24),
  [155] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__extended_string_1_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [158] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [160] = {.entry = {.count = 1, .reusable = false}}, SHIFT(24),
  [162] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [164] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [166] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [168] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [170] = {.entry = {.count = 1, .reusable = false}}, SHIFT(25),
  [172] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [174] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [176] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [178] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [180] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string_interpolation, 3, 0, 0),
  [182] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string_interpolation, 3, 0, 0),
  [184] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [186] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [188] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [190] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [192] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_blink(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "blink",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
